#cloud-config
hostname: b1-ubsrv1
manage_etc_hosts: True
system_info:
  default_user:
    name: cisco
password: cisco
chpasswd: { expire: False }
ssh_pwauth: True
ssh_authorized_keys:
  - your-ssh-pubkey-line-goes-here
network:
  version: 2
  ethernets:
    ens2:
      dhcp4: fasle
      dhcp6: false
      set-name: eth0
      addresses: [198.11.100.101/24]
      routes:
        - to: 0.0.0.0/0
          via: 198.11.100.1
      nameservers:
        addresses: [1.1.1.1, 1.0.0.1]
        search: [netlab.local]
