---
# tasks file for roles/dc1/wanrtrs/intf_config
- name: Configure interfaces
  cisco.ios.ios_interfaces:
    config:
      - name: '{{ vrf_intfs[0] }}'
        mtu: 9000
        enabled: true
      - name: '{{ vrf_intfs[1] }}'
        enabled: true
      - name: '{{ vrf_intfs[2] }}'
        enabled: true

- name: Create encapsulation on sub-interfaces
  cisco.ios.ios_config:
    lines:
      - 'encapsulation dot1Q {{ vrf_vlans[0] }}'
      - 'encapsulation dot1Q {{ vrf_vlans[1] }}'
    parents:
      - interface {{ vrf_intfs[1] }}
      - interface {{ vrf_intfs[2] }}

- name: Configure VRFs
  cisco.ios.ios_vrf:
    vrfs: '{{ vrfs }}'
  register: vrfs

- name: Configure L3 interfaces
  cisco.ios.ios_l3_interfaces:
    config:
      - name: Loopback0
        ipv4:
          - address: '{{ loopback_ips[inventory_hostname] }}'
            secondary: false
      - name: '{{ vrf_intfs[1] }}'
        ipv4:
          - address: '{{ vrf_ips[inventory_hostname]["TENANT1"] }}'
            secondary: false
      - name: '{{ vrf_intfs[2] }}'
        ipv4:
          - address: '{{ vrf_ips[inventory_hostname]["TENANT2"] }}'
            secondary: false
      - name: GigabitEthernet16
        ipv4:
          - address: '{{ mgmt_ips[inventory_hostname] }}'
            secondary: true
  register: interfaces

- name: Save running config
  cisco.ios.ios_config:
    save_when: modified
